# Generated by Django 3.2.16 on 2023-01-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
