# Generated by Django 3.2.16 on 2023-01-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_rename_release_date_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating_num',
            field=models.IntegerField(),
        ),
    ]
