# Generated by Django 3.2.16 on 2023-01-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating_all',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating_num',
            field=models.IntegerField(default=1),
        ),
    ]
