# Generated by Django 3.2.16 on 2023-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_auto_20230120_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating_num',
            field=models.IntegerField(default=0),
        ),
    ]
