# Generated by Django 3.2.16 on 2023-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_auto_20230120_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.CharField(default='<django.db.models.fields.BigAutoField>', max_length=200),
        ),
    ]
