# Generated by Django 3.2.16 on 2023-01-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_auto_20230120_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.CharField(default='<django.db.models.fields.BigAutoField>', max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
