# Generated by Django 3.2.16 on 2023-01-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_auto_20230120_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.CharField(default='<built-in function id>', max_length=200),
        ),
    ]
