# Generated by Django 3.2.16 on 2023-01-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_alter_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
    ]
