# Generated by Django 3.2.16 on 2023-01-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0017_auto_20230120_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
