# Generated by Django 3.2.16 on 2023-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0018_auto_20230120_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
