# Generated by Django 3.2.16 on 2023-01-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0020_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_belong', to='albums.album'),
        ),
    ]
